name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "fireblocks"
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ${{ vars.RUNNER }}
    permissions:
      contents: read
      packages: write
      id-token: write
    timeout-minutes: 45
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build image (Tag Release)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          CARGO_VERSION=$(grep -Po '(?<=version = ")\d+\.\d+\.\d+' Cargo.toml)
          TAG_VERSION=${GITHUB_REF#refs/tags/v}

          if [ "$CARGO_VERSION" != "$TAG_VERSION" ]; then
            echo "Version mismatch: Cargo.toml version ($CARGO_VERSION) doesn't match tag version ($TAG_VERSION)"
            exit 1
          fi
          echo "Version $CARGO_VERSION matches tag"
          IMAGE_NAME=$(echo ${{ github.repository }}  | tr '[:upper:]' '[:lower:]')
            docker build -f Dockerfile .\
            -t "${REGISTRY}/${IMAGE_NAME}:${GITHUB_SHA::6}"\
            -t "${REGISTRY}/${IMAGE_NAME}:${TAG_VERSION}"\
            -t "${REGISTRY}/${IMAGE_NAME}:latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image (Manual Dispatch)
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        run: |
          echo "Building image from manual dispatch"
          IMAGE_NAME=$(echo ${{ github.repository }}  | tr '[:upper:]' '[:lower:]')
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/[^a-zA-Z0-9._-]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
          docker build -f Dockerfile .\
            -t "${REGISTRY}/${IMAGE_NAME}:${BRANCH_NAME}"\
            -t "${REGISTRY}/${IMAGE_NAME}:${GITHUB_SHA::6}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish image
        run: |
          docker login ${REGISTRY} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
          IMAGE_NAME=$(echo ${{ github.repository }}  | tr '[:upper:]' '[:lower:]')
          docker image push --all-tags "${REGISTRY}/${IMAGE_NAME}"
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
